config/routes.rb
Rails.application.routes.draw do
  
  resources :courses do
    member do
      put "like", to: "courses#upvote"
      put "dislike", to: "courses#downvote"
    end
  end
  resources :locations
  resources :categories

  get 'sessions/new'


  get 'all/courses'

  get 'all/coordinators'

  root 'main#home'

  get 'main/home'
  
  get  'signup',  to: 'users#new'
  
  post 'signup',  to: 'users#create'
  
  resources :users
  
  get    '/login',   to: 'sessions#new'
  
  post   '/login',   to: 'sessions#create'
  
  delete '/logout',  to: 'sessions#destroy'
  
  post '/contact-us', to: 'contact#create'
  
  resources :contact

  get '/admin/course_edit', to: 'admin#course'
  
  get '/admin/coordinator_edit', to: 'admin#coordinator'

  get '/admin/category_edit', to: 'admin#category'

  get '/admin/location_edit', to: 'admin#location'
  
  get '/admin/resetvotes', to: 'admin#resetvotes'
  
  get '/likes/like', to: 'like#like'
  
  get '/likes/dislike', to: 'like#dislike'

  namespace :api do
    namespace :v1 do
      resources :users, only: :show
      resources :courses, only: :show
      namespace :list do
        resources :users, only: :index
        resources :courses, only: :index
      end
   end
  end

  get '*unmatched_route', to: 'application#not_found'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :courses_categories
  has_many :courses, through: :courses_categories

  validates :category_name, presence: true, length: { minimum: 10 }
end

app/models/contact.rb
class Contact < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i;
  validates :email, presence: true, length: { maximum: 255 },
                  format: { with: VALID_EMAIL_REGEX }

  validates :message, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :course_name, presence: true, length: { minimum: 10 }
  validates :prerequisite, presence: true, length: { minimum: 10 }
  validates :description, presence: true, length: { minimum: 10 }


  has_many :courses_categories
  has_many :courses_locations
  has_many :locations, through: :courses_locations
  has_many :categories, through: :courses_categories

  mount_uploader :picture, PictureUploader

  # acts_as_votable

  validate  :picture_size

  private

  # Validates the size of an uploaded picture.
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/models/courses_category.rb
class CoursesCategory < ApplicationRecord
  belongs_to :course
  belongs_to :category
end

app/models/courses_location.rb
class CoursesLocation < ApplicationRecord
  belongs_to :course
  belongs_to :location
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :courses_locations
  has_many :courses, through: :courses_locations

  validates :location_name, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :courses, dependent: :destroy

  before_save { self.email = email.downcase }
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w]+\.[\w]+@rmit\.edu\.au\z/i;
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # acts_as_voter
end

app/controllers/all_controller.rb
class AllController < ApplicationController
  def courses
  end

  def coordinators
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/all_helper.rb
module AllHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "rounded gravatar")
  end
end

app/views/admin/category.html.erb
<% provide(:title, "Admin") %>
<h1>Category Edit</h1>
<%if Category.all.empty?%>
  <div class="container">
    <div class="alert alert-warning center" role="alert">
      <b class="center">No Category to Edit</b>
    </div>
  </div>
<%else %>
  <div class="container media-container">
    <% Category.all.each do |c| %>
      <div class="media">
        <div class="media-body">
          <div class="content"><b>Category Name: </b><%= c.category_name %></div>
        </div>
        <div class="admin_buttons">
          <div class="link btn btn-success">
            <%= link_to 'Edit Category', edit_category_path(c) %>
          </div>
          <div class="link btn btn-success">
            <%= link_to 'Delete Category', category_path(c), method: :delete,
                        data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<%end %>

app/views/admin/coordinator.html.erb
<% provide(:title, "Admin") %>
<h1>Coordinator Edit</h1>
<%if User.all.empty?%>
  <div class="container">
    <div class="alert alert-warning center" role="alert">
      <b class="center">No Coordinators to Edit</b>
    </div>
  </div>
<%else %>
  <div class=" container coordinator_edit">
    <% User.all.each do |user| %>
      <div class=" col-md-4">
        <div class="media-body ">
        <div class="align-self-start mr-3">
          <%= gravatar_for user %>
        </div>

          <div class="content"><h4 class="media-heading"><%= user.name %></h4></div>
        </div>
        <div class="admin_buttons">
          <div class="link btn btn-success">
            <%= link_to 'Edit Coordinator', edit_user_path(user) %>
          </div>
          <div class="link btn btn-success">
            <%= link_to 'Delete Coordinator', user_path(user), method: :delete,
                        data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/admin/course.html.erb
<% provide(:title, "Admin") %>
<h1>Course Edit</h1>
<%if Course.all.empty?%>
  <div class="container">
    <div class="alert alert-warning center" role="alert">
      <b class="center">No Courses to Edit</b>
    </div>
  </div>
<%else %>
  <div class="media-container container">
    <% Course.all.each do |course_details| %>
      <div class="media ">
        <div class="media-left media-middle ">
          <div class="center">
            <%= gravatar_for course_details.user %>
            <h4 class="media-heading"> <b><%=link_to course_details.user.name, user_path(course_details.user.id) %></b></h4>
          </div>
        </div>

        <div class="media-body">
          <h4 class="media-heading"><%= link_to course_details.course_name , course_path(course_details.id)%></h4>
          <div class="content"><b>Prerequisite: </b><%= course_details.prerequisite %></div>

          <div class="content "><b>Category: </b>
            <% course_details.categories.each do |category| %>
              <div class="link"><%= link_to category.category_name, category_path(category.id) %></div>
            <% end %>
          </div>


          <div class="content "><b>Location: </b>
            <% course_details.locations.each do |location| %>
              <div class="link"><%= link_to location.location_name, location_path(location.id) %></div>
            <% end %>
          </div>

          <small class="text-muted"><%= time_ago_in_words(course_details.created_at) %> ago</small>

          <div class="thumbs-container">

            <%= link_to likes_like_path(:course => course_details.id) do %>
            <span class="like">
              <button class="like-button" style="border:none;background-color: transparent;"><i class="glyphicon glyphicon-thumbs-up"></i></button>
                <% if course_details.liked.nil?  %>
                  0
                <% else %>
                  <%= course_details.liked %>
                <% end %>
            </span>
            <% end %>

            <%= link_to likes_dislike_path(:course => course_details.id) do %>
            <span class="dislike">
              <button class="dislike-button" style="border:none;background-color: transparent;"><i class="glyphicon glyphicon-thumbs-down"></i></button>
                <% if course_details.disliked.nil?  %>
                  0
                <% else %>
                  <%= course_details.disliked %>
                <% end %>
             </span>
            <% end %>
          </div>


        </div>

        <div class="admin_buttons">
          <div class="link btn btn-success">
            <%= link_to 'Edit Course', edit_course_path(course_details) %>
          </div>
          <div class="link btn btn-success">
            <%= link_to 'Delete Course', course_path(course_details), method: :delete,
                        data: { confirm: 'Are you sure?' } %>
          </div>
          <div class="link btn btn-success">
            <%= link_to 'Reset Votes', admin_resetvotes_path(:course => course_details.id) %>
          </div>
        </div>

      </div>

    <% end %>
  </div>
<%end %>

app/views/admin/location.erb
<% provide(:title, "Admin") %>
<h1>Location Edit</h1>
<%if Location.all.empty?%>
  <div class="container">
    <div class="alert alert-warning center" role="alert">
      <b class="center">No Locations to Edit</b>
    </div>
  </div>
<%else %>
  <div class="container media-container">
    <% Location.all.each do |l| %>
      <div class="media">
        <div class="media-body">
          <div class="content"><b>Location Name: </b><%= l.location_name %></div>
        </div>
        <div class="admin_buttons">
          <div class="link btn btn-success">
            <%= link_to 'Edit Location', edit_location_path(l) %>
          </div>
          <div class="link btn btn-success">
            <%= link_to 'Delete Location', location_path(l), method: :delete,
                        data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<%end %>

app/views/layouts/_coordinators.html.erb
<%if User.all.empty?%>
  <div class="container">
    <div class="alert alert-warning center" role="alert">
      <b class="center">No Coordinators to Present</b>
    </div>
  </div>
<%else %>
  <div class="container center">
    <% User.all.each do |user| %>
      <div class="">
        <div class="media">
          <div class="align-self-start mr-3">
            <%= gravatar_for user %>
          </div>
          <div class="media-body">
            <h4 class="mt-0"><%= link_to user.name , user_path(user.id)%></h4>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<%end %>

app/views/layouts/_courses.html.erb
<%if Course.all.empty?%>
  <div class="container">
    <div class="alert alert-warning center" role="alert">
      <b class="center">No Courses to Present</b>
    </div>
  </div>
<%else %>
  <div class="media-container">
    <% Course.all.each do |course_details| %>
      <div class="media ">
      <div class="media-left media-middle ">
        <div class="center">
            <%= gravatar_for course_details.user %>
            <h4 class="media-heading"> <b><%=link_to course_details.user.name, user_path(course_details.user.id) %></b></h4>
        </div>
      </div>

      <div class="media-body">
        <h4 class="media-heading"><%= link_to course_details.course_name , course_path(course_details.id)%></h4>
        <div class="content"><b>Prerequisite: </b><%= course_details.prerequisite %></div>

        <div class="content "><b>Category: </b>
          <% course_details.categories.each do |category| %>
            <div class="link"><%= link_to category.category_name, category_path(category.id) %></div>
          <% end %>
        </div>


        <div class="content "><b>Location: </b>
          <% course_details.locations.each do |location| %>
            <div class="link"><%= link_to location.location_name, location_path(location.id) %></div>
          <% end %>
        </div>

        <small class="text-muted"><%= time_ago_in_words(course_details.created_at) %> ago</small>

        <div class="thumbs-container">

          <%= link_to likes_like_path(:course => course_details.id) do %>
          <span class="like">
            <button class="like-button" style="border:none;background-color: transparent;"><i class="glyphicon glyphicon-thumbs-up"></i></button>
            <% if course_details.liked.nil?  %>
              0
            <% else %>
              <%= course_details.liked %>
            <% end %>
          </span>
            <% end %>

            <%= link_to likes_dislike_path(:course => course_details.id) do %>
          <span class="dislike">
            <button class="dislike-button" style="border:none;background-color: transparent;"><i class="glyphicon glyphicon-thumbs-down"></i></button>
            <% if course_details.disliked.nil?  %>
              0
            <% else %>
              <%= course_details.disliked %>
            <% end %>
           </span>
            <% end %>
        </div>


      </div>
      </div>
    <% end %>
  </div>
<%end %>

app/views/layouts/_courses_categories.html.erb
<div class="media-container">
  <% Category.where(id: params[:id]).each do |categ| %>
    <% categ.courses.each do |course_details| %>
      <div class="media ">
        <div class="media-left media-middle ">
          <div class="center">
            <%= gravatar_for course_details.user %>
            <h4 class="media-heading"> <b><%=link_to course_details.user.name, user_path(course_details.user.id) %></b></h4>
          </div>
        </div>

        <div class="media-body">
          <h4 class="media-heading"><%= link_to course_details.course_name, course_path(course_details.id) %></h4>
          <div class="content"><b>Prerequisite: </b><%= course_details.prerequisite %></div>

          <div class="content "><b>Category: </b>
            <% course_details.categories.each do |category| %>
              <div class="link"><%= link_to category.category_name, category_path(category.id) %></div>
            <% end %>
          </div>


          <div class="content "><b>Location: </b>
            <% course_details.locations.each do |location| %>
              <div class="link"><%= link_to location.location_name, location_path(location.id) %></div>
            <% end %>
          </div>

          <small class="text-muted"><%= time_ago_in_words(course_details.created_at) %> ago</small>

          <div class="thumbs-container">

            <%= link_to likes_like_path(:course => course_details.id) do %>
          <span class="like">
            <button class="like-button" style="border:none;background-color: transparent;"><i class="glyphicon glyphicon-thumbs-up"></i></button>
            <% if course_details.liked.nil?  %>
              0
            <% else %>
              <%= course_details.liked %>
            <% end %>
          </span>
            <% end %>

            <%= link_to likes_dislike_path(:course => course_details.id) do %>
          <span class="dislike">
            <button class="dislike-button" style="border:none;background-color: transparent;"><i class="glyphicon glyphicon-thumbs-down"></i></button>
            <% if course_details.disliked.nil?  %>
              0
            <% else %>
              <%= course_details.disliked %>
            <% end %>
           </span>
            <% end %>
          </div>


        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_courses_locations.html.erb
<div class="media-container">
  <% Location.where(id: params[:id]).each do |loc| %>
    <% loc.courses.each do |course_details| %>
      <div class="media ">
        <div class="media-left media-middle ">
          <div class="center">
            <%= gravatar_for course_details.user %>
            <h4 class="media-heading"> <b><%=link_to course_details.user.name, user_path(course_details.user.id) %></b></h4>
          </div>
        </div>

        <div class="media-body">
          <h4 class="media-heading"><%= link_to course_details.course_name, course_path(course_details.id) %></h4>
          <div class="content"><b>Prerequisite: </b><%= course_details.prerequisite %></div>

          <div class="content "><b>Category: </b>
            <% course_details.categories.each do |category| %>
              <div class="link"><%= link_to category.category_name, category_path(category.id) %></div>
            <% end %>
          </div>


          <div class="content "><b>Location: </b>
            <% course_details.locations.each do |location| %>
              <div class="link"><%= link_to location.location_name, location_path(location.id) %></div>
            <% end %>
          </div>

          <small class="text-muted"><%= time_ago_in_words(course_details.created_at) %> ago</small>

          <div class="thumbs-container">

             <%= link_to likes_like_path(:course => course_details.id) do %>
          <span class="like">
            <button class="like-button" style="border:none;background-color: transparent;"><i class="glyphicon glyphicon-thumbs-up"></i></button>
            <% if course_details.liked.nil?  %>
              0
            <% else %>
              <%= course_details.liked %>
            <% end %>
          </span>
            <% end %>

            <%= link_to likes_dislike_path(:course => course_details.id) do %>
          <span class="dislike">
            <button class="dislike-button" style="border:none;background-color: transparent;"><i class="glyphicon glyphicon-thumbs-down"></i></button>
            <% if course_details.disliked.nil?  %>
              0
            <% else %>
              <%= course_details.disliked %>
            <% end %>
           </span>
            <% end %>
          </div>


        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer ">
   <nav class="jumbotron">
     <div class=" container-fluid">
       <div class=" row">
         <div class="col-md-4">
           <h2>General inquires</h2>
           <li><%= mail_to "s3761295@student.rmit.edu.au", "Andy Song" %></li>
           <li><%= mail_to "s3761295@student.rmit.edu.au", "Junilang Jiang" %></li>
           <li><%= mail_to "s3761295@student.rmit.edu.au", "Ali" %></li>
         </div>
         <div class="col-md-4">
           <h2>Useful Links</h2>
           <li><%= link_to "RMIT Courses",     "https://maps.google.com" %></li>
           <li><%= link_to "RMIT Help Desk",     "https://www.gmail.com" %></li>
           <li><%= link_to "RMIT International",    "https://rmit.com" %></li>
         </div>
         <div class="col-md-4">
           <h2>Media</h2>
           <li><%= link_to '<i class="fa fa-home"></i> Home'.html_safe,     root_path %></li>
           <li><%= link_to '<i class="fa fa-send"></i> Gmail'.html_safe,     "https://www.gmail.com" %></li>
           <li><%= link_to '<i class="fa fa-facebook"></i> Facebook'.html_safe,    "https://facebook.com" %></li>
           <li><%= link_to '<i class="fa fa-twitter"></i> Twitter'.html_safe,    "https://twitter.com" %></li>
           <li><%= link_to '<i class="fa fa-snapchat-ghost"></i> Snapchat'.html_safe,    "https://snapchat.com" %></li>
         </div>
       </div>
     </div>
   </nav>
 </footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top">
  <div class="container">
    <%if logged_in? %>
      <%= link_to "course app",  all_courses_path, id: "logo" %>
    <%else %>
      <%= link_to "course app", root_path, id: "logo" %>
    <%end %>

    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-clone"></i> Category
          </a>
          <ul class="dropdown-menu">
            <% Category.all.each do |c| %>
              <li class="dropdown-item"><%= link_to c.category_name, category_path(c.id) %></li>
            <% end %>
            <% if logged_in? %>
              <li class="divider"></li>
              <li>
                <%= link_to "Create Category", new_category_path %>
              </li>
              <% end %>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-map-marker"></i> Locations
          </a>
          <ul class="dropdown-menu">
            <% Location.all.each do |l| %>
              <li><%= link_to l.location_name, location_path(l.id) %></li>
            <% end %>
            <% if logged_in? %>
              <li class="divider"></li>
              <li>
                <%= link_to "Create Location", new_location_path %>
              </li>
            <% end %>
          </ul>
        </li>

        <% if logged_in? %>
          <li><%= link_to "New Course", new_course_path %></li>

          <% if is_admin %>
            <li class="dropdown">
              <a href="#" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-admin"></i> Dashboard
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Course Edit", admin_course_edit_path %></li>
                <li><%= link_to "Category Edit", admin_category_edit_path %></li>
                <li><%= link_to "Location Edit", admin_location_edit_path %></li>
                <li><%= link_to "Coordinator Edit", admin_coordinator_edit_path %></li>
              </ul>
            </li>
          <%end %>

          <li class="dropdown">
            <a href="#" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-user"></i> User
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
        
        <li>
          <%= link_to "Contact Us", contact_index_path %>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_tabs.html.erb
<div class="container" role="navigation">
    <%if current_page?(all_courses_path) %>
      <ul class="nav nav-tabs">
        <li role="presentation" class="active"><%= link_to "Course", :back %></li>
        <li role="presentation"><%= link_to "Coordinator", all_coordinators_path %></li>
      </ul>
      <%= render 'layouts/courses' %>
    <%elsif current_page?(all_coordinators_path)%>
      <ul class="nav nav-tabs">
        <li role="presentation"><%= link_to "Course", :back %></li>
        <li role="presentation" class="active"><%= link_to "Coordinator", all_coordinators_path %></li>
      </ul>
      <%= render 'layouts/coordinators' %>
    <%elsif current_page?(category_path) %>
      <ul class="nav nav-tabs">
        <li role="presentation" class="active"><%= link_to "Course", :back %></li>
        <li role="presentation"><%= link_to "Coordinator", all_coordinators_path %></li>
      </ul>
      <%= render 'layouts/courses_categories' %>
  <%elsif current_page?(location_path) %>
    <ul class="nav nav-tabs">
      <li role="presentation" class="active"><%= link_to "Course", :back %></li>
      <li role="presentation"><%= link_to "Coordinator", all_coordinators_path %></li>
    </ul>
    <%= render 'layouts/courses_locations' %>
    <%end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%= render 'layouts/header' %>
     <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
  </body>
  <%= render 'layouts/footer' %>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>