config/routes.rb
Rails.application.routes.draw do
  
  resources :courses do
    member do
      put "like", to: "courses#upvote"
      put "dislike", to: "courses#downvote"
    end
  end
  resources :locations
  resources :categories

  get 'sessions/new'


  get 'all/courses'

  get 'all/coordinators'

  root 'main#home'

  get 'main/home'
  
  get  'signup',  to: 'users#new'
  
  post 'signup',  to: 'users#create'
  
  resources :users
  
  get    '/login',   to: 'sessions#new'
  
  post   '/login',   to: 'sessions#create'
  
  delete '/logout',  to: 'sessions#destroy'
  
  post '/contact-us', to: 'contact#create'
  
  resources :contact

  get '/admin/course_edit', to: 'admin#course'
  
  get '/admin/coordinator_edit', to: 'admin#coordinator'

  get '/admin/category_edit', to: 'admin#category'

  get '/admin/location_edit', to: 'admin#location'
  
  get '/admin/resetvotes', to: 'admin#resetvotes'
  
  get '/likes/like', to: 'like#like'
  
  get '/likes/dislike', to: 'like#dislike'

  namespace :api do
    namespace :v1 do
      resources :users, only: :show
      resources :courses, only: :show
      namespace :list do
        resources :users, only: :index
        resources :courses, only: :index
      end
   end
  end

  get '*unmatched_route', to: 'application#not_found'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :courses_categories
  has_many :courses, through: :courses_categories

  validates :category_name, presence: true, length: { minimum: 10 }
end

app/models/contact.rb
class Contact < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i;
  validates :email, presence: true, length: { maximum: 255 },
                  format: { with: VALID_EMAIL_REGEX }

  validates :message, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :course_name, presence: true, length: { minimum: 10 }
  validates :prerequisite, presence: true, length: { minimum: 10 }
  validates :description, presence: true, length: { minimum: 10 }


  has_many :courses_categories
  has_many :courses_locations
  has_many :locations, through: :courses_locations
  has_many :categories, through: :courses_categories

  mount_uploader :picture, PictureUploader

  # acts_as_votable

  validate  :picture_size

  private

  # Validates the size of an uploaded picture.
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/models/courses_category.rb
class CoursesCategory < ApplicationRecord
  belongs_to :course
  belongs_to :category
end

app/models/courses_location.rb
class CoursesLocation < ApplicationRecord
  belongs_to :course
  belongs_to :location
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :courses_locations
  has_many :courses, through: :courses_locations

  validates :location_name, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :courses, dependent: :destroy

  before_save { self.email = email.downcase }
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w]+\.[\w]+@rmit\.edu\.au\z/i;
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # acts_as_voter
end

app/controllers/all_controller.rb
class AllController < ApplicationController
  def courses
  end

  def coordinators
  end
end

app/controllers/api/v1/list/users_controller.rb
class Api::V1::List::UsersController < ApiController
  def index
    @users = User.all
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApiController
  before_action :set_user
  def show
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  before_action :set_default_format

  private

  def set_default_format
    request.format = :json
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper
  def show
    @user = User.find(params[:id])
  end

  def new
    if session[:user_id]
      @user = User.find(session[:user_id])
    end
    if @user
      redirect_to @user
    else
      @user = User.new
    end
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    if  !can_edit_update_user
      flash[:danger] = "Not authorized"
      redirect_to root_path
    end
    @user = helpers.current_user
  end

  def update
    if  !can_edit_update_user
      flash[:danger] = "Not authorized"
      redirect_to root_path
    end
    @user = helpers.current_user
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    if !is_admin
      flash[:danger] = "Not authorized"
      redirect_to root_path
    else
      @user = User.find(params[:id])
      @user.destroy
      flash[:success] = "User is successfully deleted"
      redirect_to admin_coordinator_edit_path
    end
  end
  
  def edit
    @user = helpers.current_user
  end
  
  def update
    @user = helpers.current_user
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/all_helper.rb
module AllHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
  def whereCondition (condition="")
    return "category=" + "\'#{condition}\'" if controller.controller_name == "category"
    return "location_name=" + "\'#{condition}\'" if controller.controller_name == "location"
    return condition
  end
  
  def full_title(page_title = '')
    base_title = "Course App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def is_admin
    # redirect_to root_path, alert: "Not authorized" if
    return (current_user.nil? or current_user.admin?)
  end

  def user_own_course
    # redirect_to root_path, alert: "Not authorized" if
    return @course.user.id == current_user.id
  end


  def can_edit_update_user
    if current_user
      return true if (params[:id] == current_user.id.to_s)
      return true if (current_user.admin == true)
    end
  end

  def can_edit_update
    if current_user
      return true if (current_user.admin == true)
      return true if (@course.user.id == current_user.id)
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "rounded gravatar")
  end
end

app/views/users/edit.html.erb
<% provide(:title, "Edit Profile") %>

<h1>Edit Profile</h1>

<div class="container-form">
  <%= form_for(@user) do |f| %>
      
      <%= render 'shared/error_messages' %>
      
      <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="field">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <div class="field">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
      </div>

      <%= f.submit "Change Details", class: "btn btn-success" %>
    <% end %>

</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Coordinator Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
     <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary",style: "margin-top: 20px;" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "User Profile") %>
<div class="container center">
  <div class="user_info">
    <%= gravatar_for @user %>
    <h1><%= @user.name %></h1>
  </div>
</div>
<% if @user.id == current_user.id %>
  <h1> Courses Created By Me</h1>
<%else %>
  <h1> Courses Created By <%= @user.name %></h1>
<%end %>
<div class="container ">
  <div class="media-container">
    <%if !@user.courses.empty?%>
    <% @user.courses.each do |course_details| %>
      <div class="media ">
        <div class="media-body">
          <h4 class="media-heading"><%= link_to course_details.course_name , course_path(course_details.id)%></h4>
          <div class="content"><b>Prerequisite: </b><%= course_details.prerequisite %></div>

          <small class="text-muted"><%= time_ago_in_words(course_details.created_at) %> ago</small>
          <div class="thumbs-container">
          <span class="like">
            <button class="like-button" style="border:none;background-color: transparent;"><i class="glyphicon glyphicon-thumbs-up"></i></button> 0
          </span>
            <span class="dislike">
            <button class="dislike-button" style="border:none;background-color: transparent;"><i class="glyphicon glyphicon-thumbs-down"></i></button> 0
          </span>
          </div>
        </div>

        <div class="admin_buttons">
          <% if (@user.id == current_user.id) or is_admin %>
            <div class="link btn btn-success">
              <%= link_to 'Edit Course', edit_course_path(course_details) %>
            </div>
            <% if is_admin %>
              <div class="link btn btn-success">
                <%= link_to 'Delete Course', course_path(course_details), method: :delete,
                            data: { confirm: 'Are you sure?' } %>
              </div>
            <%end %>
          <%end %>
        </div>
      </div>
    <% end %>
    <%else %>
      <div class="alert alert-warning center" role="alert">
        <b class="center">This is no Courses created by the user</b>
      </div>
    <%end %>
  </div>
</div>