config/routes.rb
Rails.application.routes.draw do
  
  resources :courses do
    member do
      put "like", to: "courses#upvote"
      put "dislike", to: "courses#downvote"
    end
  end
  resources :locations
  resources :categories

  get 'sessions/new'


  get 'all/courses'

  get 'all/coordinators'

  root 'main#home'

  get 'main/home'
  
  get  'signup',  to: 'users#new'
  
  post 'signup',  to: 'users#create'
  
  resources :users
  
  get    '/login',   to: 'sessions#new'
  
  post   '/login',   to: 'sessions#create'
  
  delete '/logout',  to: 'sessions#destroy'
  
  post '/contact-us', to: 'contact#create'
  
  resources :contact

  get '/admin/course_edit', to: 'admin#course'
  
  get '/admin/coordinator_edit', to: 'admin#coordinator'

  get '/admin/category_edit', to: 'admin#category'

  get '/admin/location_edit', to: 'admin#location'
  
  get '/admin/resetvotes', to: 'admin#resetvotes'
  
  get '/likes/like', to: 'like#like'
  
  get '/likes/dislike', to: 'like#dislike'

  namespace :api do
    namespace :v1 do
      resources :users, only: :show
      resources :courses, only: :show
      namespace :list do
        resources :users, only: :index
        resources :courses, only: :index
      end
   end
  end

  get '*unmatched_route', to: 'application#not_found'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :courses_categories
  has_many :courses, through: :courses_categories

  validates :category_name, presence: true, length: { minimum: 10 }
end

app/models/contact.rb
class Contact < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i;
  validates :email, presence: true, length: { maximum: 255 },
                  format: { with: VALID_EMAIL_REGEX }

  validates :message, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :course_name, presence: true, length: { minimum: 10 }
  validates :prerequisite, presence: true, length: { minimum: 10 }
  validates :description, presence: true, length: { minimum: 10 }


  has_many :courses_categories
  has_many :courses_locations
  has_many :locations, through: :courses_locations
  has_many :categories, through: :courses_categories

  mount_uploader :picture, PictureUploader

  # acts_as_votable

  validate  :picture_size

  private

  # Validates the size of an uploaded picture.
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/models/courses_category.rb
class CoursesCategory < ApplicationRecord
  belongs_to :course
  belongs_to :category
end

app/models/courses_location.rb
class CoursesLocation < ApplicationRecord
  belongs_to :course
  belongs_to :location
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :courses_locations
  has_many :courses, through: :courses_locations

  validates :location_name, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :courses, dependent: :destroy

  before_save { self.email = email.downcase }
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w]+\.[\w]+@rmit\.edu\.au\z/i;
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # acts_as_voter
end

app/controllers/all_controller.rb
class AllController < ApplicationController
  def courses
  end

  def coordinators
  end
end

app/controllers/api/v1/courses_controller.rb
class Api::V1::CoursesController < ApiController
  before_action :set_course
  def show
  end

  private
  def set_course
    @course = Course.find(params[:id])
  end
end

app/controllers/api/v1/list/courses_controller.rb
class Api::V1::List::CoursesController < ApiController
  def index
    @courses = Course.all
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  before_action :set_default_format

  private

  def set_default_format
    request.format = :json
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  include ApplicationHelper
  require 'aws-sdk-s3'
  # before_action :is_admin, only: [:new, :edit, :update, :destroy]
  # before_action :user_own_course, only: [:edit, :update]

  # GET /courses
  # GET /courses.json
  def index
    redirect_to all_courses_path
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    if !logged_in?
      flash[:danger] = "Not authorized"
      redirect_to root_path
      return
    end
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit

    if !can_edit_update
      flash[:danger] = "Not authorized"
      redirect_to root_path
      return
    end
    # @user = helpers.current_user
    # @course = Course.find(params[:id])
    #
    # if @user.id == @course.user_id
    #   permitted_columns = params.permit(:course_name, :prerequisite, :description)
    #   @course.update_attributes(permitted_columns)
    #   redirect_back fallback_location: root_path
    # end
  end


  # POST /courses
  # POST /courses.json
  def create
    if !logged_in?
      flash[:danger] = "Not authorized"
      redirect_to root_path
      return
    end

    @course = Course.new(course_params)
    @course.user_id = current_user.id

      if @course.save
        flash[:success] = "Course was successfully created."
        redirect_to course_path(@course.id)
      else
        render :new
        # format.json { render json: @course.errors, status: :unprocessable_entity }
        flash[:danger] = @course.errors.full_messages
        # @course.errors.each {|e| flash.now[:danger] = e}
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    if !can_edit_update
      flash[:danger] = "Not authorized"
      redirect_to root_path
      return
    end
    if @course.update(course_params)
      flash[:success] = "Course was successfully updated."
      redirect_to course_path(@course.id)
    else
      flash[:danger] = "Something went wrong!"
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    if !is_admin
      flash[:danger] = "Not authorized"
      redirect_to root_path
    else
      @course.destroy
      flash[:success] = "Course is successfully deleted"
      redirect_to admin_course_edit_path
    end
  end

  def upvote
    @course = Course.find(params[:id])
    if !@course.voted_up_by?(current_user)
      @course.upvote_by current_user
    else
      flash[:danger] = 'You can only vote up a course once!'
    end
    redirect_back fallback_location: root_path
  end

  def downvote
    @course = Course.find(params[:id])
    if !@course.voted_down_by?(current_user)
      @course.downvote_by current_user
    else
      flash[:danger] = 'You can only vote down a course once!'
    end
    redirect_back fallback_location: root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
      # @picture = Course.find(params[:picture])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit!
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/all_helper.rb
module AllHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "rounded gravatar")
  end
end

app/views/courses/_form.html.erb
 <div class="container-form">
    <%= form_with(model: course, local: true) do |form| %>
      <% if course.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <ul>
            <% course.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

        <div class="field">
          <%= form.label :course_name %>
          <%= form.text_field :course_name, id: :course_course_name %>
        </div>

        <div class="field">
          <%= form.label :prerequisite %>
          <%= form.text_field :prerequisite, id: :course_prerequisite %>
        </div>

        <div class="field">
          <%= form.label :description %>
          <%= form.text_area :description, id: :course_description %>
        </div>

        <div class="checkbox-container">
          <b>Category: </b>
            <%= hidden_field_tag 'course[category_ids][]', nil %>
            <% Category.all.each do |category| %>
            <div class="checkbox">
              <%= check_box_tag 'course[category_ids][]', category.id, @course.categories.include?(category) %>
              <%= category.category_name %>
              </div>
            <% end %>
        </div>


        <div class="checkbox-container">
          <b>Location: </b>

            <%= hidden_field_tag "course[location_ids][]", nil %>
            <% Location.all.each do |location| %>
            <div class="checkbox">
                <%= check_box_tag "course[location_ids][]", location.id, @course.locations.include?(location) %>
                <%= location.location_name%>
            </div>
            <% end %>

        </div>

      <span class="picture">
        <%= form.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </span>


      <div class="actions">
        <%= form.submit :class => 'btn-success'%>
      </div>
    <% end %>
    <script type="text/javascript">
       $('#micropost_picture').bind('change', function() {
           var size_in_megabytes = this.files[0].size/1024/1024;
           if (size_in_megabytes > 5) {
               alert('Maximum file size is 5MB. Please choose a smaller file.');
           }
       });
    </script>
</div>

app/views/courses/edit.html.erb
<% provide(:title, "Edit Course") %>
<h1>Edit Course</h1>

<%= render 'form', course: @course %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Course name</th>
      <th>Prerequisite</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.course_name %></td>
        <td><%= course.prerequisite %></td>
        <td><%= course.description %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<% provide(:title, "New Course") %>
<h1>New Course</h1>

<%= render 'form', course: @course %>

app/views/courses/show.html.erb
<% provide(:title, "Course Details") %>
<div class="courses-show">
  <div class="container media-container">
    <div class="center">
      <h1 class="media-heading"><%=@course.course_name%></h1>
      <%= image_tag @course.picture.url if @course.picture? %>
    </div>
      <div class="media">


        <div class="media-body">
          <div class="content"><b>Prerequisite: </b><%= @course.prerequisite %></div>

          <div class="content "><b>Category: </b>
            <% @course.categories.each do |category| %>
              <div class="link"><%= link_to category.category_name, category_path(category.id) %></div>
            <% end %>
          </div>


          <div class="content "><b>Location: </b>
            <% @course.locations.each do |location| %>
              <div class="link"><%= link_to location.location_name, location_path(location.id) %></div>
            <% end %>
          </div>

          <div class="content ">
            <b>Course Description: </b>
            <div class="course-description"><br><%= @course.description%><br> </div>
          </div>

          <div class="thumbs-container">

            <%= link_to likes_like_path(:course => @course.id) do %>
            <span class="like">
              <button class="like-button" style="border:none;background-color: transparent;"><i class="glyphicon glyphicon-thumbs-up"></i></button>
                <% if @course.liked.nil?  %>
                  0
                <% else %>
                  <%= @course.liked %>
                <% end %>
            </span>
            <% end %>

            <%= link_to likes_dislike_path(:course => @course.id) do %>
            <span class="dislike">
              <button class="dislike-button" style="border:none;background-color: transparent;"><i class="glyphicon glyphicon-thumbs-down"></i></button>
                <% if @course.disliked.nil?  %>
                  0
                <% else %>
                  <%= @course.disliked %>
                <% end %>
             </span>
            <% end %>
          </div>

        </div>
        <div class="media-right media-middle ">
          <div class="center">
            <%= gravatar_for @course.user %>
            <h4 class="media-heading"> <b><span>Brought to you by:</span> <%=link_to @course.user.name, user_path(@course.user.id) %></b></h4>
          </div>
        </div>


        <div class="admin_buttons">
          <% if can_edit_update %>
            <div class="link btn btn-success">
              <%= link_to 'Edit Course', edit_course_path(@course) %>
            </div>
            <%if is_admin %>
              <div class="link btn btn-success">
                <%= link_to 'Delete Course', course_path(@course), method: :delete,
                            data: { confirm: 'Are you sure?' } %>
              </div>
              <div class="link btn btn-success">
                <a> Rest Votes </a>
              </div>
            <%end %>
          <%end %>
        </div>
      </div>
  </div>
</div>